# Generated by Django 3.1.1 on 2020-12-04 22:47

from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imageit.models.CropItImageField(max_height=300, max_width=300, null=True, quality=100, upload_to='profile_pics', upscale=False),
        ),
    ]
