# Generated by Django 3.1.1 on 2020-09-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
