# Generated by Django 3.1.1 on 2020-09-06 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 0, 10, 29, 786201, tzinfo=utc)),
        ),
    ]
