# Generated by Django 3.1.12 on 2021-06-18 07:03

import blogs.models
from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=imageit.models.CropItImageField(blank=True, null=True, upload_to=blogs.models.Blog.get_upload_path),
        ),
    ]
