# Generated by Django 3.1.1 on 2020-09-06 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumnaill',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 1, 31, 20, 302827, tzinfo=utc)),
        ),
    ]
