# Generated by Django 3.1.1 on 2020-09-06 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200906_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 23, 1, 40, 582626, tzinfo=utc)),
        ),
    ]
