# Generated by Django 3.1.1 on 2020-09-07 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200906_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pubished_on',
            new_name='published_on',
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 0, 3, 22, 218933, tzinfo=utc)),
        ),
    ]
