# Generated by Django 3.1.1 on 2020-10-27 22:35

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200925_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(null=True, upload_to=blogs.models.Blog.get_upload_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=blogs.models.Blog.get_upload_path),
        ),
    ]
