# Generated by Django 3.1.1 on 2020-10-28 23:03

import blogs.models
from django.db import migrations
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20201028_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=images.models.CustomImageField(blank=True, null=True, upload_to=blogs.models.Blog.get_upload_path),
        ),
    ]
