# Generated by Django 3.1.1 on 2020-11-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test',
        ),
    ]
