# Generated by Django 3.1.1 on 2020-12-03 23:35

import blogs.models
from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_remove_blog_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=imageit.models.ScaleItImageField(blank=True, max_height=250, max_width=250, null=True, quality=100, upload_to=blogs.models.Blog.get_upload_path, upscale=False),
        ),
    ]
