# Generated by Django 3.1.1 on 2020-12-04 22:01

import blogs.models
from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20201203_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=imageit.models.ScaleItImageField(blank=True, null=True, upload_to=blogs.models.Blog.get_upload_path),
        ),
    ]
