# Generated by Django 3.1.1 on 2020-12-05 00:16

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20201204_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contentNew',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
