# Generated by Django 3.1.1 on 2020-12-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_blog_contentnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
    ]
