# Generated by Django 3.1.1 on 2021-01-07 22:43

import blogs.models
from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20201207_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=imageit.models.ScaleItImageField(upload_to=blogs.models.BlogImage.get_upload_path),
        ),
    ]
