# Generated by Django 3.1.1 on 2020-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropzoneit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropzoneitmodel',
            name='object_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
