# Generated by Django 3.1.1 on 2020-11-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dropzoneit', '0002_dropzoneitmodel_object_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DropZoneItModel',
            new_name='DropZoneIt',
        ),
    ]
